### ISSUE TITLE
version.texi, version-remake.texi are missing 

### ISSUE THREAD

**Issue by guangyu-shi** [rocky/remake#37] opened 2018-05-10 18:07 UTC
Copied from the console:

make.texi:5: @include: could not find version.texi

remake.texi:35: @include: could not find version-remake.texi

Bliss,
--Gary

**Comment by rocky** [comment] 2018-05-11 16:10
Those files are derived. This is all automake and its texinfoweirdness. Hey, why not use remake to figure out how to get them remade?

**Comment by guangyu-shi** [comment] 2018-05-11 18:58
I meet the issue when trying to build remake from git

$ $SHELL ./autogen.sh
...

$ ./configure && make && make check && sudo make install 

it stops in the middle and fails to build remake.

After pulling version.texi from the source of make and create version-remake.texi, the issue gets solved.

Bliss,
--Gary

**Comment by guangyu-shi** [comment] 2018-05-13 17:47
I meet the issue when trying to build remake from git

$ $SHELL ./autogen.sh
...

$ ./configure && make && make check && sudo make install 

it stops in the middle and fails to build remake.

After pulling version.texi from the source of make and create version-remake.texi, the issue gets solved.

Bliss,
--Gary

**Comment by zhanjf** [comment] 2018-11-23 05:52
I met the same issue. Just like shi, after changing the file name of doc from version.texi to version-remake.texi, the issue gets solved.

**Comment by zfields** [comment] 2019-01-24 20:15
**`root@be9fc6075bd6:/remake-release-remake-4.2.1-dbg-1.4# remake --trace`**
```
Reading makefiles...
Updating goal targets....
 File 'all' does not exist.
   Prerequisite 'stamp-h1' is newer than target 'config.h'.
  Must remake target 'config.h'.
Makefile:660: update target 'config.h' due to: stamp-h1
##>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
test -f config.h || rm -f stamp-h1
##<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
##>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
test -f config.h || remake  stamp-h1
##<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
  Successfully remade target file 'config.h'.
Must remake target 'all'.
Makefile:621: update target 'all' due to: config.h
##>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
remake  all-recursive
##<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
Reading makefiles...
Updating goal targets....
 File 'all-recursive' does not exist.
Must remake target 'all-recursive'.
remake[1]: Entering directory '/remake-release-remake-4.2.1-dbg-1.4'
Makefile:916: target 'all-recursive' does not exist
##>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
fail=; \
if (target_option=k; case ${target_option-} in ?) ;; *) echo "am__make_running_with_option: internal error: invalid" "target option '${target_option-}' specified" >&2; exit 1;; esac; has_opt=no; sane_makeflags=$MAKEFLAGS; if { if test -z '1'; then false; elif test -n 'x86_64-pc-linux-gnu'; then true; elif test -n '4.1+dbg1.1' && test -n '/remake-release-remake-4.2.1-dbg-1.4'; then true; else false; fi; }; then sane_makeflags=$MFLAGS; else case $MAKEFLAGS in *\\[\ \ ]*) bs=\\; sane_makeflags=`printf '%s\n' "$MAKEFLAGS"| sed "s/$bs$bs[$bs $bs ]*//g"`;; esac; fi; skip_next=no; strip_trailopt () { flg=`printf '%s\n' "$flg" | sed "s/$1.*$//"`; }; for flg in $sane_makeflags; do test $skip_next = yes && { skip_next=no; continue; }; case $flg in *=*|--*) continue;; -*I) strip_trailopt 'I'; skip_next=yes;; -*I?*) strip_trailopt 'I';; -*O) strip_trailopt 'O'; skip_next=yes;; -*O?*) strip_trailopt 'O';; -*l) strip_trailopt 'l'; skip_next=yes;; -*l?*) strip_trailopt 'l';; -[dEDm]) skip_next=yes;; -[JT]) skip_next=yes;; esac; case $flg in *$target_option*) has_opt=yes; break;; esac; done; test $has_opt = yes); then \
  failcom='fail=yes'; \
else \
  failcom='exit 1'; \
fi; \
dot_seen=no; \
target=`echo all-recursive | sed s/-recursive//`; \
case "all-recursive" in \
  distclean-* | maintainer-clean-*) list='glob config po doc w32 unittest' ;; \
  *) list='glob config po doc  unittest' ;; \
esac; \
for subdir in $list; do \
  echo "Making $target in $subdir"; \
  if test "$subdir" = "."; then \
    dot_seen=yes; \
    local_target="$target-am"; \
  else \
    local_target="$target"; \
  fi; \
  (CDPATH="${ZSH_VERSION+.}:" && cd $subdir && remake  $local_target) \
  || eval $failcom; \
done; \
if test "$dot_seen" = "no"; then \
  remake  "$target-am" || exit 1; \
fi; test -z "$fail"
##<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
Making all in glob
Reading makefiles...
Updating goal targets....
 File 'all' does not exist.
   File 'all-am' does not exist.
  Must remake target 'all-am'.
  Successfully remade target file 'all-am'.
Must remake target 'all'.
Successfully remade target file 'all'.
remake[2]: Entering directory '/remake-release-remake-4.2.1-dbg-1.4/glob'
remake[2]: Nothing to be done for 'all'.
remake[2]: Leaving directory '/remake-release-remake-4.2.1-dbg-1.4/glob'
Making all in config
Reading makefiles...
Updating goal targets....
 File 'all' does not exist.
   File 'all-am' does not exist.
  Must remake target 'all-am'.
  Successfully remade target file 'all-am'.
Must remake target 'all'.
Successfully remade target file 'all'.
remake[2]: Entering directory '/remake-release-remake-4.2.1-dbg-1.4/config'
remake[2]: Nothing to be done for 'all'.
remake[2]: Leaving directory '/remake-release-remake-4.2.1-dbg-1.4/config'
Making all in po
Reading makefiles...
Updating goal targets....
 File 'all' does not exist.
   File 'all-yes' does not exist.
  Must remake target 'all-yes'.
  Successfully remade target file 'all-yes'.
Must remake target 'all'.
Successfully remade target file 'all'.
remake[2]: Entering directory '/remake-release-remake-4.2.1-dbg-1.4/po'
remake[2]: Nothing to be done for 'all'.
remake[2]: Leaving directory '/remake-release-remake-4.2.1-dbg-1.4/po'
Making all in doc
Reading makefiles...
Updating goal targets....
 File 'all' does not exist.
   File 'all-am' does not exist.
     File 'make.info' does not exist.
       File 'version.texi' does not exist.
      Must remake target 'version.texi'.
      Successfully remade target file 'version.texi'.
    Must remake target 'make.info'.
remake[2]: Entering directory '/remake-release-remake-4.2.1-dbg-1.4/doc'
Makefile:400: update target 'make.info' due to: make.texi version.texi fdl.texi make-stds.texi
##>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
restore=: && backupdir=".am$$" && \
am__cwd=`pwd` && CDPATH="${ZSH_VERSION+.}:" && cd . && \
rm -rf $backupdir && mkdir $backupdir && \
if (/bin/bash /remake-release-remake-4.2.1-dbg-1.4/config/missing makeinfo --version) >/dev/null 2>&1; then \
  for f in make.info make.info-[0-9] make.info-[0-9][0-9] make.i[0-9] make.i[0-9][0-9]; do \
    if test -f $f; then mv $f $backupdir; restore=mv; else :; fi; \
  done; \
else :; fi && \
cd "$am__cwd"; \
if /bin/bash /remake-release-remake-4.2.1-dbg-1.4/config/missing makeinfo   -I . \
 -o make.info make.texi; \
then \
  rc=0; \
  CDPATH="${ZSH_VERSION+.}:" && cd .; \
else \
  rc=$?; \
  CDPATH="${ZSH_VERSION+.}:" && cd . && \
  $restore $backupdir/* `echo "./make.info" | sed 's|[^/]*$||'`; \
fi; \
rm -rf $backupdir; exit $rc
##<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
make.texi:5: @include: could not find version.texi
make.texi:24: warning: undefined flag: UPDATED
make.texi:25: warning: undefined flag: VERSION
make.texi:64: warning: undefined flag: VERSION
make.texi:65: warning: undefined flag: UPDATED-MONTH
Makefile:400: recipe for target 'make.info' failed
Makefile:442: *** [make.info] Error 1

#0  make.info at /remake-release-remake-4.2.1-dbg-1.4/doc/Makefile:442
#1  all-am at /remake-release-remake-4.2.1-dbg-1.4/doc/Makefile:663
#2  all at /remake-release-remake-4.2.1-dbg-1.4/doc/Makefile:365
remake[2]: Leaving directory '/remake-release-remake-4.2.1-dbg-1.4/doc'
Makefile:916: recipe for target 'all-recursive' failed
Makefile:915: *** [all-recursive] Error 1

#0  all-recursive at /remake-release-remake-4.2.1-dbg-1.4/Makefile:915
remake[1]: Leaving directory '/remake-release-remake-4.2.1-dbg-1.4'
Makefile:621: recipe for target 'all' failed
Makefile:620: *** [all] Error 2

#0  all at /remake-release-remake-4.2.1-dbg-1.4/Makefile:620
```

**Comment by zfields** [comment] 2019-01-24 20:18
**root@be9fc6075bd6:/remake-release-remake-4.2.1-dbg-1.4# find . -name "*.texi"
```
./doc/make-stds.texi
./doc/remake.texi
./doc/fdl.texi
./doc/make.texi
```

**Comment by rocky** [comment] 2019-01-25 00:48
Maybe using `remake` and its debugging you can offer a solution to this?

**Comment by zfields** [comment] 2019-01-25 11:15
I did use `remake --trace` and I pasted the output (_above_), as well as offered an intermediate solution.

**PROBLEM:** You are failing to add, copy, create, etc..., the following two files:

```
<remake repo>/doc/version.texi
<remake repo>/doc/version-remake.texi
```

I have identified the build bug and have provided you with everything you need to know to address it.

**Comment by rocky** [comment] 2019-01-25 11:43
On this one, I think I am going to wait on a PR.

**Comment by zfields** [comment] 2019-01-25 12:36
Maybe if we put our heads together we can come up with a solution.

To start, I don't know anything about `version.texi` or `version-remake.texi`. Do you know the purpose of those files?

You must have had them at some point, or you wouldn't have been able to build `remake` yourself.

Do you know if the files supposed to be generated or downloaded, or if they are source files?

The fix I have demonstrated proves the files only need to exist (albeit completely empty) in order to allow the build to succeed.

The files are currently listed in your `.gitignore`, so if you do have them locally, they will never be checked in to your repository. Is that desired?

Once I understand a little more about the nature of the files, then perhaps I can be of more assistance.

**Comment by rocky** [comment] 2019-01-26 22:08
`version.texi` is described [here](https://www.gnu.org/software/automake/manual/html_node/Texinfo.html). 

As far as I can tell, it looks like automake has only one provision for one document built per folder. But what if as in the cases here there are two docs - one for `make` and one for the `remake` changes? Then what do you do? 

I suppose one solution would be to create a folder per document. I suppose that is a possibility. What I have instead done here is add `version-remake.texi` that is supposed to work like `version.texi`. 

Note however that the problem reported is not just with `version-remake.texi` but `version.texi` as well; and  the automake system is supposed to take care of on its own. 

> The files are currently listed in your .gitignore

Yes, that is how it should be since these are derived in the automake system.

**Comment by zfields** [comment] 2019-01-28 20:12
To make sure I'm understanding you correctly, you are requesting that `automake` generate two files (`version.texi` and `version-remake.texi`) and because it only expects to create one it is erroring and not making either file?

**Comment by rocky** [comment] 2019-01-28 20:39
I am requesting that whatever solution is used 
* it is consistent with whatever the automake conventions are, since we are using automake for the rest of the project (and this is what GNU make uses)
* that there be two documents one for GNU make, and one for the remake changes

Other that, go at it.

**Comment by zfields** [comment] 2019-01-29 16:02
You should use the `help wanted` tag to indicate to others you need help fixing this bug. I do not know enough about `automake` to help you. I was trying to help you clearly state the scope of the help you need as you understand it (_above_).

**Comment by boretom** [comment] 2020-02-08 22:19
Is that still an issue? Well, I had a look into it anyway and found the following:

After running the first command, `autoreconfig -f -i` there exist Makefile targets for version.texi and version-remake.texi in doc/Makefile.in.

   $(srcdir)/version.texi: @MAINTAINER_MODE_TRUE@ $(srcdir)/stamp-vti

and

   $(srcdir)/version-remake.texi: @MAINTAINER_MODE_TRUE@ $(srcdir)/stamp-1

These targets run only if MAINTAINER_MODE_TRUE is set which would mean calling `./configure --enable-maintainer-mode` is required.

On macOS and FreeBSD 12.0 that way version.texi and version-remake.texi were created while building the remake executable and as a result no errors concerning version-*.texi.

Would someone being able to verify this using the following build instructions:

````
   $ cd remake*
   $ autoreconf -f -i
   $ ./configure --enable-maintainer-mode
   $ make po-update
   $ make && make check
````
If confirmed to work I'll create an simple PR to adjust INSTALL-from-source.md

**Comment by rocky** [comment] 2020-02-08 23:55
@boretom the shell script `autogen.sh` does these steps.

**Comment by boretom** [comment] 2020-02-09 08:59
@rocky yes I did see that but it also contains `(cd doc && make stamp-1 stamp-vti)` which would not be needed if. But maybe I'm completely missing the point of this issue.

I'm not sure what commands exactly the original author (@guangyu-shi) ran. But if ./configure really was run again after autogen.sh that would explain it.

And in INSTALL-from-source.md under **Building** ./configure is listed without the --enable-maintainer-mode, that may lead to confusion.

The least confusing would probably be setting the `AM_MAINTAINER_MODE` to `enable` per default in configure.ac (see [AM_MAINTAINER_MODE doc](https://www.gnu.org/software/automake//manual/html_node/maintainer_002dmode.html)) by replacing `AM_MAINTAINER_MODE` with `AM_MAINTAINER_MODE([enable])`. That way ./configure with no arguments would work.

**Comment by rocky** [comment] 2020-02-09 11:53
I am not sure what the issue is here either. Perhaps everything is fixed. 

If maintainer mode is enabled by default, then running `make` you need some sort of texinfo installed, and that setting will the bleed into the final tarball which shouldn't require texinfo.

**Comment by boretom** [comment] 2020-02-09 13:55
@rocky, Sorry if I'm a bit slow: Can you compile remake without needing texinfo? I haven't managed to do that. Even `make dist` will need `makeinfo` at some point.

**Comment by rocky** [comment] 2020-02-09 14:04
Yes, if you build from a dist tarball. Maintainers make "dists",  tarballs, and users don't make necessarily make dists, although they could if they had additional tools.

**Comment by rocky** [comment] 2020-02-09 14:07
In general, yes this stuff is arcane and has lots of possibilites and edge cases. So my take is not to mess with it to try to "improve" it. If you want to document it better, sure, that's harmless.

In the past by doing when I've tried to "improve" it, I was mucking with autotools conventions. So in a sense you make stuff better for one class of users while making it "worse" (by violating convention) for others which often are the packagers.

There is much more important stuff to do than futzing with this, in my opionon.

**Comment by boretom** [comment] 2020-02-09 14:11
Sure, I let it go :) ... I'm a bit too OCD to have longstanding issue open, but I'll manage :)

**Comment by rocky** [comment] 2020-02-09 14:15
Ok. Closing this issue since I think it is fixed. If not we can reopen it with more up-to-date comments about what needs to be done.

**Closed by rocky** 2020-02-09 14:15 UTC
